### ISSUE TITLE
ERROR: loading failed for 'i386' on windows

### ISSUE THREAD

**Issue by DejanDraschkow** [mne-tools/mne-r#5]
first of all - amazing work! thanks! 

I am getting into trouble when trying to install the package on two different windows machines (iOS works perfectly well).  

```
Error: loading failed
Execution halted
*** arch - x64
Importing MNE version=0.17.dev0, path='C:\Users\Public\ANACON~1\lib\site-packages\mne'
ERROR: loading failed for 'i386'
```
this is in response to ```devtools::install_github("mne-tools/mne-r")```

I am trying to troubleshoot this at the moment, but maybe somebody has an idea? 
It seems to be defaulting to the wrong python version during installation. 

thanks,
dejan

**Comment by dengemann** [comment]
@DejanDraschkow the question is what exactly fails. Can you import mne inside python? Could it be that you use a 32 bit version of R? Perhaps update the R installation. This is what apparently worked for @craddm.

**Comment by craddm** [comment]
@DejanDraschkow the problem, I think, is that if both 32-bit and 64-bit versions of R are installed, `devtools` tries to build for both of them. During the build process, it checks if the newly built package can be loaded under both 32-bit and 64-bit R versions. When it tries running the 32-bit version, the `reticulate` package causes an error if the version of Python it has access to is 64-bit, so the install process fails. I think the key part of the update which spared me this problem was not installing the 32-bit version of R, as now `devtools` only builds for 64-bit.

Rather than having to update R, you can add INSTALL_opts=c("--no-multiarch") to your `install_github()` call:
`devtools::install_github("mne-tools/mne-r", INSTALL_opts=c("--no-multiarch"))`

This should force it to only build the package for your currently running R version.

edit: Actually, I suspect this might also happen because `reticulate` is loaded by the `mne-r` package itself using `library(reticulate)` , which it shouldn't be

**Comment by DejanDraschkow** [comment]
perfect, this worked :) 
and yes, the issue might be connected to loading reticulate in the package

**Comment by dengemann** [comment]
This looks like something we should document in the troubleshooting section here https://mne-tools.github.io/mne-r/index.html#troubleshooting-and-known-issues-
